from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_closedLoop(object):
    def setupUi(self, closedLoop):
        closedLoop.setObjectName(_fromUtf8("closedLoop"))
        closedLoop.resize(400,300)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))

        self.enable0 = QtGui.QPushButton(self.dockWidgetContents)
        self.enable0.setObjectName(_fromUtf8("enable0"))
        self.enable0.setCheckable(True)
        self.gridLayout.addWidget(self.enable0, 0, 0, 1, 8)

        self.enable1 = QtGui.QPushButton(self.dockWidgetContents)
        self.enable1.setObjectName(_fromUtf8("enable1"))
        self.enable1.setCheckable(True)
        self.gridLayout.addWidget(self.enable1, 1, 0, 1, 8)


        self.ch1Label = QtGui.QLabel(self.dockWidgetContents)
        self.ch1Label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ch1Label.setObjectName(_fromUtf8("ch1Label"))
        self.gridLayout.addWidget(self.ch1Label, 2, 3, 1, 1)
        self.ch1 = QtGui.QSpinBox(self.dockWidgetContents)
        self.ch1.setMinimum(0)
        self.ch1.setMaximum(127)
        self.ch1.setSingleStep(1)
        self.ch1.setProperty("value", 0)
        self.ch1.setObjectName(_fromUtf8("ch1"))
        self.gridLayout.addWidget(self.ch1, 2, 4, 1, 1)

        # self.ch2Label = QtGui.QLabel(self.dockWidgetContents)
        # self.ch2Label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        # self.ch2Label.setObjectName(_fromUtf8("ch2Label"))
        # self.gridLayout.addWidget(self.ch2Label, 3, 2, 1, 1)
        # self.ch2 = QtGui.QSpinBox(self.dockWidgetContents)
        # self.ch2.setMinimum(0)
        # self.ch2.setMaximum(127)
        # self.ch2.setSingleStep(1)
        # self.ch2.setProperty("value", 0)
        # self.ch2.setObjectName(_fromUtf8("ch2"))
        # self.gridLayout.addWidget(self.ch2, 3, 3, 1, 1)

        # self.ch3Label = QtGui.QLabel(self.dockWidgetContents)
        # self.ch3Label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        # self.ch3Label.setObjectName(_fromUtf8("ch3Label"))
        # self.gridLayout.addWidget(self.ch3Label, 3, 4, 1, 1)
        # self.ch3 = QtGui.QSpinBox(self.dockWidgetContents)
        # self.ch3.setMinimum(0)
        # self.ch3.setMaximum(127)
        # self.ch3.setSingleStep(1)
        # self.ch3.setProperty("value", 0)
        # self.ch3.setObjectName(_fromUtf8("ch3"))
        # self.gridLayout.addWidget(self.ch3, 3, 5, 1, 1)

        # self.ch4Label = QtGui.QLabel(self.dockWidgetContents)
        # self.ch4Label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        # self.ch4Label.setObjectName(_fromUtf8("ch4Label"))
        # self.gridLayout.addWidget(self.ch4Label, 3, 6, 1, 1)
        # self.ch4 = QtGui.QSpinBox(self.dockWidgetContents)
        # self.ch4.setMinimum(0)
        # self.ch4.setMaximum(127)
        # self.ch4.setSingleStep(1)
        # self.ch4.setProperty("value", 0)
        # self.ch4.setObjectName(_fromUtf8("ch4"))
        # self.gridLayout.addWidget(self.ch4, 3, 7, 1, 1)

        self.ch1EnableLabel = QtGui.QLabel(self.dockWidgetContents)
        self.ch1EnableLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.ch1EnableLabel.setObjectName(_fromUtf8("ch1EnableLabel"))
        self.gridLayout.addWidget(self.ch1EnableLabel, 3, 3, 1, 1)
        self.ch1Enable = QtGui.QComboBox(self.dockWidgetContents)
        self.ch1Enable.setEditable(False)
        self.ch1Enable.setMaxVisibleItems(3)
        self.ch1Enable.setObjectName(_fromUtf8("ch1Enable"))
        self.ch1Enable.addItem(_fromUtf8(""))
        self.ch1Enable.addItem(_fromUtf8(""))
        self.ch1Enable.addItem(_fromUtf8(""))
        self.ch1Enable.setCurrentIndex(0)
        self.gridLayout.addWidget(self.ch1Enable, 3, 4, 1, 1)

        # self.ch2EnableLabel = QtGui.QLabel(self.dockWidgetContents)
        # self.ch2EnableLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        # self.ch2EnableLabel.setObjectName(_fromUtf8("ch2EnableLabel"))
        # self.gridLayout.addWidget(self.ch2EnableLabel, 4, 2, 1, 1)
        # self.ch2Enable = QtGui.QComboBox(self.dockWidgetContents)
        # self.ch2Enable.setEditable(False)
        # self.ch2Enable.setMaxVisibleItems(3)
        # self.ch2Enable.setObjectName(_fromUtf8("ch2Enable"))
        # self.ch2Enable.addItem(_fromUtf8(""))
        # self.ch2Enable.addItem(_fromUtf8(""))
        # self.ch2Enable.addItem(_fromUtf8(""))
        # self.ch2Enable.setCurrentIndex(0)
        # self.gridLayout.addWidget(self.ch2Enable, 4, 3, 1, 1)

        # self.ch3EnableLabel = QtGui.QLabel(self.dockWidgetContents)
        # self.ch3EnableLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        # self.ch3EnableLabel.setObjectName(_fromUtf8("ch3EnableLabel"))
        # self.gridLayout.addWidget(self.ch3EnableLabel, 4, 4, 1, 1)
        # self.ch3Enable = QtGui.QComboBox(self.dockWidgetContents)
        # self.ch3Enable.setEditable(False)
        # self.ch3Enable.setMaxVisibleItems(3)
        # self.ch3Enable.setObjectName(_fromUtf8("ch3Enable"))
        # self.ch3Enable.addItem(_fromUtf8(""))
        # self.ch3Enable.addItem(_fromUtf8(""))
        # self.ch3Enable.addItem(_fromUtf8(""))
        # self.ch3Enable.setCurrentIndex(0)
        # self.gridLayout.addWidget(self.ch3Enable, 4, 5, 1, 1)

        # self.ch4EnableLabel = QtGui.QLabel(self.dockWidgetContents)
        # self.ch4EnableLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        # self.ch4EnableLabel.setObjectName(_fromUtf8("ch4EnableLabel"))
        # self.gridLayout.addWidget(self.ch4EnableLabel, 4, 6, 1, 1)
        # self.ch4Enable = QtGui.QComboBox(self.dockWidgetContents)
        # self.ch4Enable.setEditable(False)
        # self.ch4Enable.setMaxVisibleItems(3)
        # self.ch4Enable.setObjectName(_fromUtf8("ch4Enable"))
        # self.ch4Enable.addItem(_fromUtf8(""))
        # self.ch4Enable.addItem(_fromUtf8(""))
        # self.ch4Enable.addItem(_fromUtf8(""))
        # self.ch4Enable.setCurrentIndex(0)
        # self.gridLayout.addWidget(self.ch4Enable, 4, 7, 1, 1)

        self.threshold1Label = QtGui.QLabel(self.dockWidgetContents)
        self.threshold1Label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.threshold1Label.setObjectName(_fromUtf8("threshold1Label"))
        self.gridLayout.addWidget(self.threshold1Label, 4, 3, 1, 1)
        self.threshold1 = QtGui.QSpinBox(self.dockWidgetContents)
        self.threshold1.setMinimum(0)
        self.threshold1.setMaximum(2**16 - 1)
        self.threshold1.setSingleStep(1)
        self.threshold1.setProperty("value", 0)
        self.threshold1.setObjectName(_fromUtf8("threshold1"))
        self.gridLayout.addWidget(self.threshold1, 4, 4, 1, 1)

        self.freq1Label = QtGui.QLabel(self.dockWidgetContents)
        self.freq1Label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.freq1Label.setObjectName(_fromUtf8("freq1Label"))
        self.gridLayout.addWidget(self.freq1Label, 2, 5, 1, 1)
        self.freq1 = QtGui.QSpinBox(self.dockWidgetContents)
        self.freq1.setMinimum(0)
        self.freq1.setMaximum(500)
        self.freq1.setSingleStep(1)
        self.freq1.setProperty("value", 0)
        self.freq1.setObjectName(_fromUtf8("freq1"))
        self.gridLayout.addWidget(self.freq1, 2, 6, 1, 1)

        self.freq2Label = QtGui.QLabel(self.dockWidgetContents)
        self.freq2Label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.freq2Label.setObjectName(_fromUtf8("freq2Label"))
        self.gridLayout.addWidget(self.freq2Label, 3, 5, 1, 1)
        self.freq2 = QtGui.QSpinBox(self.dockWidgetContents)
        self.freq2.setMinimum(0)
        self.freq2.setMaximum(500)
        self.freq2.setSingleStep(1)
        self.freq2.setProperty("value", 0)
        self.freq2.setObjectName(_fromUtf8("freq2"))
        self.gridLayout.addWidget(self.freq2, 3, 6, 1, 1)


        # self.threshold2Label = QtGui.QLabel(self.dockWidgetContents)
        # self.threshold2Label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        # self.threshold2Label.setObjectName(_fromUtf8("threshold2Label"))
        # self.gridLayout.addWidget(self.threshold2Label, 5, 2, 1, 1)
        # self.threshold2 = QtGui.QSpinBox(self.dockWidgetContents)
        # self.threshold2.setMinimum(0)
        # self.threshold2.setMaximum(127)
        # self.threshold2.setSingleStep(1)
        # self.threshold2.setProperty("value", 0)
        # self.threshold2.setObjectName(_fromUtf8("threshold2"))
        # self.gridLayout.addWidget(self.threshold2, 5, 3, 1, 1)

        # self.threshold3Label = QtGui.QLabel(self.dockWidgetContents)
        # self.threshold3Label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        # self.threshold3Label.setObjectName(_fromUtf8("threshold3Label"))
        # self.gridLayout.addWidget(self.threshold3Label, 5, 4, 1, 1)
        # self.threshold3 = QtGui.QSpinBox(self.dockWidgetContents)
        # self.threshold3.setMinimum(0)
        # self.threshold3.setMaximum(127)
        # self.threshold3.setSingleStep(1)
        # self.threshold3.setProperty("value", 0)
        # self.threshold3.setObjectName(_fromUtf8("threshold3"))
        # self.gridLayout.addWidget(self.threshold3, 5, 5, 1, 1)

        # self.threshold4Label = QtGui.QLabel(self.dockWidgetContents)
        # self.threshold4Label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        # self.threshold4Label.setObjectName(_fromUtf8("threshold4Label"))
        # self.gridLayout.addWidget(self.threshold4Label, 5, 6, 1, 1)
        # self.threshold4 = QtGui.QSpinBox(self.dockWidgetContents)
        # self.threshold4.setMinimum(0)
        # self.threshold4.setMaximum(127)
        # self.threshold4.setSingleStep(1)
        # self.threshold4.setProperty("value", 0)
        # self.threshold4.setObjectName(_fromUtf8("threshold4"))
        # self.gridLayout.addWidget(self.threshold4, 5, 7, 1, 1)

        self.deadLabel = QtGui.QLabel(self.dockWidgetContents)
        self.deadLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.deadLabel.setObjectName(_fromUtf8("deadLabel"))
        self.gridLayout.addWidget(self.deadLabel, 2, 1, 1, 1)
        self.deadLength = QtGui.QSpinBox(self.dockWidgetContents)
        self.deadLength.setMinimum(0)
        self.deadLength.setMaximum(2**16 - 1)
        self.deadLength.setSingleStep(1)
        self.deadLength.setProperty("value", 0)
        self.deadLength.setObjectName(_fromUtf8("deadLength"))
        self.gridLayout.addWidget(self.deadLength, 2, 2, 1, 1)

        self.randomMode = QtGui.QCheckBox(self.dockWidgetContents)
        self.randomMode.setCheckable(True)
        self.randomMode.setObjectName(_fromUtf8("randomMode"))
        self.gridLayout.addWidget(self.randomMode, 2, 0, 1, 1)

        self.chStimLabel = QtGui.QLabel(self.dockWidgetContents)
        self.chStimLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.chStimLabel.setObjectName(_fromUtf8("chStimLabel"))
        self.gridLayout.addWidget(self.chStimLabel, 3, 1, 1, 1)
        self.chStim = QtGui.QSpinBox(self.dockWidgetContents)
        self.chStim.setMinimum(0)
        self.chStim.setMaximum(127)
        self.chStim.setSingleStep(1)
        self.chStim.setProperty("value", 0)
        self.chStim.setObjectName(_fromUtf8("chStim"))
        self.gridLayout.addWidget(self.chStim, 3, 2, 1, 1)

        self.nfftLabel = QtGui.QLabel(self.dockWidgetContents)
        self.nfftLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.nfftLabel.setObjectName(_fromUtf8("nfftLabel"))
        self.gridLayout.addWidget(self.nfftLabel, 4, 1, 1, 1)
        self.nfft = QtGui.QComboBox(self.dockWidgetContents)
        self.nfft.setEditable(False)
        self.nfft.setMaxVisibleItems(8)
        self.nfft.setObjectName(_fromUtf8("nfft"))
        self.nfft.addItem(_fromUtf8(""))
        self.nfft.addItem(_fromUtf8(""))
        self.nfft.addItem(_fromUtf8(""))
        self.nfft.addItem(_fromUtf8(""))
        self.nfft.addItem(_fromUtf8(""))
        self.nfft.addItem(_fromUtf8(""))
        self.nfft.addItem(_fromUtf8(""))
        self.nfft.addItem(_fromUtf8(""))
        self.nfft.setCurrentIndex(0)
        self.gridLayout.addWidget(self.nfft, 4, 2, 1, 1) 

        closedLoop.setWidget(self.dockWidgetContents)

        self.nfft.setCurrentIndex(4)
        self.chStim.setValue(29)
        self.ch1.setValue(28)
        self.threshold1.setValue(1000)
        self.ch1Enable.setCurrentIndex(1)
        self.freq1.setValue(20)
        self.freq2.setValue(20)

        self.retranslateUi(closedLoop)
        QtCore.QMetaObject.connectSlotsByName(closedLoop)

    def retranslateUi(self, closedLoop):
        closedLoop.setWindowTitle(_translate("closedLoop", "Closed Loop Control", None))

        self.enable0.setText(_translate("closedLoop", "Enable NM0 Closed Loop Stim", None))
        self.enable1.setText(_translate("closedLoop", "Enable NM1 Closed Loop Stim", None))

        self.ch1Label.setText(_translate("closedLoop", "Recording Channel:", None))
        # self.ch2Label.setText(_translate("closedLoop", "Recording Channel:", None))
        # self.ch3Label.setText(_translate("closedLoop", "Recording Channel:", None))
        # self.ch4Label.setText(_translate("closedLoop", "Recording Channel:", None))

        self.ch1EnableLabel.setText(_translate("closedLoop", "Stim when:", None))
        # self.ch2EnableLabel.setText(_translate("closedLoop", "Stim when:", None))
        # self.ch3EnableLabel.setText(_translate("closedLoop", "Stim when:", None))
        # self.ch4EnableLabel.setText(_translate("closedLoop", "Stim when:", None))

        self.ch1Enable.setItemText(0, _translate("closedLoop", "Never", None))
        self.ch1Enable.setItemText(1, _translate("closedLoop", "Above", None))
        self.ch1Enable.setItemText(2, _translate("closedLoop", "Below", None))

        # self.ch2Enable.setItemText(0, _translate("closedLoop", "Never", None))
        # self.ch2Enable.setItemText(1, _translate("closedLoop", "Above", None))
        # self.ch2Enable.setItemText(2, _translate("closedLoop", "Below", None))

        # self.ch3Enable.setItemText(0, _translate("closedLoop", "Never", None))
        # self.ch3Enable.setItemText(1, _translate("closedLoop", "Above", None))
        # self.ch3Enable.setItemText(2, _translate("closedLoop", "Below", None))

        # self.ch4Enable.setItemText(0, _translate("closedLoop", "Never", None))
        # self.ch4Enable.setItemText(1, _translate("closedLoop", "Above", None))
        # self.ch4Enable.setItemText(2, _translate("closedLoop", "Below", None))

        self.threshold1Label.setText(_translate("closedLoop", "Threshold:", None))
        # self.threshold2Label.setText(_translate("closedLoop", "Threshold:", None))
        # self.threshold3Label.setText(_translate("closedLoop", "Threshold:", None))
        # self.threshold4Label.setText(_translate("closedLoop", "Threshold:", None))

        self.deadLabel.setText(_translate("closedLoop", "Dead Length:", None))
        self.chStimLabel.setText(_translate("closedLoop", "Stim Channel:", None))

        self.randomMode.setText(_translate("closedLoop", "Random (Control) Mode", None))
        self.nfftLabel.setText(_translate("closedLoop", "NFFT:", None))
        self.nfft.setItemText(0, _translate("closedLoop", "16", None))
        self.nfft.setItemText(1, _translate("closedLoop", "32", None))
        self.nfft.setItemText(2, _translate("closedLoop", "64", None))
        self.nfft.setItemText(3, _translate("closedLoop", "128", None))
        self.nfft.setItemText(4, _translate("closedLoop", "256", None))
        self.nfft.setItemText(5, _translate("closedLoop", "512", None))
        self.nfft.setItemText(6, _translate("closedLoop", "1024", None))
        self.nfft.setItemText(7, _translate("closedLoop", "2048", None))
        self.freq1Label.setText(_translate("closedLoop", "Frequency Min:", None))
        self.freq2Label.setText(_translate("closedLoop", "Frequency Max:", None))

