# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stimconfig.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StimConfig(object):
    def setupUi(self, StimConfig):
        StimConfig.setObjectName(_fromUtf8("StimConfig"))
        StimConfig.resize(980, 325)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StimConfig.sizePolicy().hasHeightForWidth())
        StimConfig.setSizePolicy(sizePolicy)
        StimConfig.setMinimumSize(QtCore.QSize(941, 325))
        StimConfig.setMaximumSize(QtCore.QSize(524287, 325))
        self.dockWidgetContents_main = QtGui.QWidget()
        self.dockWidgetContents_main.setObjectName(_fromUtf8("dockWidgetContents_main"))
        self.dockWidgetContents_main.setStyleSheet('font-size: 12pt;')

        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_main)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents_main)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setGeometry(QtCore.QRect(0,0,950,305))
        self.dockWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))

        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pchgModCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.pchgModCheck.setObjectName(_fromUtf8("pchgModCheck"))
        self.gridLayout.addWidget(self.pchgModCheck, 8, 3, 1, 1)
        self.clBox = QtGui.QComboBox(self.dockWidgetContents)
        self.clBox.setObjectName(_fromUtf8("clBox"))
        self.gridLayout.addWidget(self.clBox, 4, 12, 1, 1)
        self.stimBiasLabel = QtGui.QLabel(self.dockWidgetContents)
        self.stimBiasLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stimBiasLabel.setObjectName(_fromUtf8("stimBiasLabel"))
        self.gridLayout.addWidget(self.stimBiasLabel, 8, 11, 1, 1)
        self.blkAllCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.blkAllCheck.setObjectName(_fromUtf8("blkAllCheck"))
        self.gridLayout.addWidget(self.blkAllCheck, 8, 2, 1, 1)
        self.stimFrequencyLabel = QtGui.QLabel(self.dockWidgetContents)
        self.stimFrequencyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stimFrequencyLabel.setObjectName(_fromUtf8("stimFrequencyLabel"))
        self.gridLayout.addWidget(self.stimFrequencyLabel, 6, 11, 1, 1)
        self.testEnCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.testEnCheck.setObjectName(_fromUtf8("testEnCheck"))
        self.gridLayout.addWidget(self.testEnCheck, 11, 5, 1, 1)
        self.testSelCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.testSelCheck.setObjectName(_fromUtf8("testSelCheck"))
        self.gridLayout.addWidget(self.testSelCheck, 11, 6, 1, 1)
        self.nccpLabel = QtGui.QLabel(self.dockWidgetContents)
        self.nccpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nccpLabel.setObjectName(_fromUtf8("nccpLabel"))
        self.gridLayout.addWidget(self.nccpLabel, 5, 11, 1, 1)
        self.nccpBox = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.nccpBox.setSuffix(_fromUtf8(""))
        self.nccpBox.setDecimals(0)
        self.nccpBox.setMinimum(0.0)
        self.nccpBox.setMaximum(63.0)
        self.nccpBox.setSingleStep(1.0)
        self.nccpBox.setProperty("value", 0.0)
        self.nccpBox.setObjectName(_fromUtf8("nccpBox"))
        self.gridLayout.addWidget(self.nccpBox, 5, 12, 1, 1)
        self.stimMultLabel = QtGui.QLabel(self.dockWidgetContents)
        self.stimMultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stimMultLabel.setObjectName(_fromUtf8("stimMultLabel"))
        self.gridLayout.addWidget(self.stimMultLabel, 2, 11, 1, 1)
        self.clLabel = QtGui.QLabel(self.dockWidgetContents)
        self.clLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.clLabel.setObjectName(_fromUtf8("clLabel"))
        self.gridLayout.addWidget(self.clLabel, 4, 11, 1, 1)
        self.stimBiasBox = RoundedSpinBox(self.dockWidgetContents)
        self.stimBiasBox.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.stimBiasBox.setDecimals(0)
        self.stimBiasBox.setMinimum(45.0)
        self.stimBiasBox.setMaximum(150.0)
        self.stimBiasBox.setSingleStep(15.0)
        self.stimBiasBox.setObjectName(_fromUtf8("stimBiasBox"))
        self.gridLayout.addWidget(self.stimBiasBox, 8, 12, 1, 1)
        self.hrcLabel = QtGui.QLabel(self.dockWidgetContents)
        self.hrcLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hrcLabel.setObjectName(_fromUtf8("hrcLabel"))
        self.gridLayout.addWidget(self.hrcLabel, 3, 11, 1, 1)
        self.stimMultBox = QtGui.QComboBox(self.dockWidgetContents)
        self.stimMultBox.setObjectName(_fromUtf8("stimMultBox"))
        self.gridLayout.addWidget(self.stimMultBox, 2, 12, 1, 1)
        self.hrcBox = QtGui.QComboBox(self.dockWidgetContents)
        self.hrcBox.setObjectName(_fromUtf8("hrcBox"))
        self.gridLayout.addWidget(self.hrcBox, 3, 12, 1, 1)
        self.prCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.prCheck.setObjectName(_fromUtf8("prCheck"))
        self.gridLayout.addWidget(self.prCheck, 9, 6, 1, 1)
        self.gndResCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.gndResCheck.setObjectName(_fromUtf8("gndResCheck"))
        self.gridLayout.addWidget(self.gndResCheck, 9, 1, 1, 1)
        self.refPdCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.refPdCheck.setObjectName(_fromUtf8("refPdCheck"))
        self.gridLayout.addWidget(self.refPdCheck, 8, 1, 1, 1)
        self.pkgRetCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.pkgRetCheck.setObjectName(_fromUtf8("pkgRetCheck"))
        self.gridLayout.addWidget(self.pkgRetCheck, 8, 5, 1, 1)
        self.pkgPdCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.pkgPdCheck.setObjectName(_fromUtf8("pkgPdCheck"))
        self.gridLayout.addWidget(self.pkgPdCheck, 9, 2, 1, 1)
        self.cgndCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.cgndCheck.setObjectName(_fromUtf8("cgndCheck"))
        self.gridLayout.addWidget(self.cgndCheck, 8, 6, 1, 1)
        self.polCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.polCheck.setObjectName(_fromUtf8("polCheck"))
        self.gridLayout.addWidget(self.polCheck, 9, 5, 1, 1)
        self.regBiasCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.regBiasCheck.setObjectName(_fromUtf8("regBiasCheck"))
        self.gridLayout.addWidget(self.regBiasCheck, 11, 1, 1, 1)
        self.gmBiasCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.gmBiasCheck.setToolTip(_fromUtf8(""))
        self.gmBiasCheck.setObjectName(_fromUtf8("gmBiasCheck"))
        self.gridLayout.addWidget(self.gmBiasCheck, 11, 2, 1, 1)
        self.gmPulseCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.gmPulseCheck.setEnabled(True)
        self.gmPulseCheck.setObjectName(_fromUtf8("gmPulseCheck"))
        self.gridLayout.addWidget(self.gmPulseCheck, 11, 3, 1, 1)
        self.noCheckCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.noCheckCheck.setObjectName(_fromUtf8("noCheckCheck"))
        self.gridLayout.addWidget(self.noCheckCheck, 11, 4, 1, 1)
        self.stopModeCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.stopModeCheck.setObjectName(_fromUtf8("stopModeCheck"))
        self.gridLayout.addWidget(self.stopModeCheck, 8, 4, 1, 1)
        self.doffCheck = QtGui.QCheckBox(self.dockWidgetContents)
        self.doffCheck.setObjectName(_fromUtf8("doffCheck"))
        self.gridLayout.addWidget(self.doffCheck, 9, 3, 1, 1)
        self.stimFrequencyBox = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.stimFrequencyBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stimFrequencyBox.setDecimals(4)
        self.stimFrequencyBox.setMinimum(3.91)
        self.stimFrequencyBox.setMaximum(67.8438)
        self.stimFrequencyBox.setSingleStep(0.0625)
        self.stimFrequencyBox.setProperty("value", 3.91)
        self.stimFrequencyBox.setObjectName(_fromUtf8("stimFrequencyBox"))
        self.gridLayout.addWidget(self.stimFrequencyBox, 6, 12, 1, 1)
        self.writeRegs = QtGui.QPushButton(self.dockWidgetContents)
        self.writeRegs.setObjectName(_fromUtf8("writeRegs"))
        self.gridLayout.addWidget(self.writeRegs, 9, 12, 1, 1)
        self.waveformConfigButton = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waveformConfigButton.sizePolicy().hasHeightForWidth())
        self.waveformConfigButton.setSizePolicy(sizePolicy)
        self.waveformConfigButton.setObjectName(_fromUtf8("waveformConfigButton"))
        self.gridLayout.addWidget(self.waveformConfigButton, 0, 1, 1, 6)

        self.scrollArea.setWidget(self.dockWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        StimConfig.setWidget(self.dockWidgetContents_main)

        self.retranslateUi(StimConfig)
        QtCore.QMetaObject.connectSlotsByName(StimConfig)

    def retranslateUi(self, StimConfig):
        StimConfig.setWindowTitle(_translate("StimConfig", "Stimulation Configuration", None))
        self.pchgModCheck.setText(_translate("StimConfig", "Use diode offset", None))
        self.stimBiasLabel.setText(_translate("StimConfig", "Stim. Bias", None))
        self.blkAllCheck.setText(_translate("StimConfig", "Block All", None))
        self.stimFrequencyLabel.setText(_translate("StimConfig", "Stim. Period", None))
        self.testEnCheck.setText(_translate("StimConfig", "Test enable", None))
        self.testSelCheck.setToolTip(_translate("StimConfig", "T: compliance voltage; 0: mirror headroom", None))
        self.testSelCheck.setText(_translate("StimConfig", "Test select", None))
        self.nccpLabel.setText(_translate("StimConfig", "# of comp. pulses", None))
        self.stimMultLabel.setText(_translate("StimConfig", "Stim. Multiplier", None))
        self.clLabel.setText(_translate("StimConfig", "Compliance Level", None))
        self.stimBiasBox.setSuffix(_translate("StimConfig", " nA", None))
        self.hrcLabel.setText(_translate("StimConfig", "Headroom Control", None))
        self.prCheck.setToolTip(_translate("StimConfig", "T: monophasic; F: biphasic", None))
        self.prCheck.setText(_translate("StimConfig", "Monophasic", None))
        self.gndResCheck.setText(_translate("StimConfig", "Bypass ref R", None))
        self.refPdCheck.setText(_translate("StimConfig", "Ref to 10M R", None))
        self.pkgRetCheck.setText(_translate("StimConfig", "Package return", None))
        self.pkgPdCheck.setText(_translate("StimConfig", "Bypass pkg R", None))
        self.cgndCheck.setText(_translate("StimConfig", "GND Counter", None))
        self.polCheck.setText(_translate("StimConfig", "Bipolar", None))
        self.regBiasCheck.setText(_translate("StimConfig", "Use external bias", None))
        self.gmBiasCheck.setText(_translate("StimConfig", "Use constant-gm", None))
        self.gmPulseCheck.setText(_translate("StimConfig", "Force gm startup", None))
        self.noCheckCheck.setText(_translate("StimConfig", "Disable error check", None))
        self.stopModeCheck.setText(_translate("StimConfig", "Short during e-stop", None))
        self.doffCheck.setToolTip(_translate("StimConfig", "T: one diode; F: two diodes", None))
        self.doffCheck.setText(_translate("StimConfig", "Use 1 diode", None))
        self.stimFrequencyBox.setPrefix(_translate("StimConfig", "value Hz (", None))
        self.stimFrequencyBox.setSuffix(_translate("StimConfig", " ms)", None))
        self.writeRegs.setText(_translate("StimConfig", "Write Stim. Registers", None))
        self.waveformConfigButton.setText(_translate("StimConfig", "Waveform Configuration", None))

from roundedspinbox import RoundedSpinBox
