# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wfmdialog.ui'
#
# Created: Thu Jul 30 17:07:05 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WaveformDialog(object):
    def setupUi(self, WaveformDialog):
        WaveformDialog.setObjectName(_fromUtf8("WaveformDialog"))
        WaveformDialog.setWindowModality(QtCore.Qt.WindowModal)
        WaveformDialog.resize(645, 426)
        WaveformDialog.setModal(False)
        self.verticalLayout = QtGui.QVBoxLayout(WaveformDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(WaveformDialog)
        self.splitter.setAutoFillBackground(False)
        self.splitter.setStyleSheet(_fromUtf8("QSplitter::handle { background-color: rgb(216, 216, 216) }\n"
"\n"
""))
        self.splitter.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(3)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.waveformSelectionFrame = QtGui.QFrame(self.splitter)
        self.waveformSelectionFrame.setEnabled(True)
        self.waveformSelectionFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.waveformSelectionFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.waveformSelectionFrame.setObjectName(_fromUtf8("waveformSelectionFrame"))
        self.gridLayout = QtGui.QGridLayout(self.waveformSelectionFrame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.delWaveformButton = QtGui.QPushButton(self.waveformSelectionFrame)
        self.delWaveformButton.setAutoDefault(False)
        self.delWaveformButton.setObjectName(_fromUtf8("delWaveformButton"))
        self.gridLayout.addWidget(self.delWaveformButton, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.addWaveformButton = QtGui.QPushButton(self.waveformSelectionFrame)
        self.addWaveformButton.setAutoDefault(False)
        self.addWaveformButton.setObjectName(_fromUtf8("addWaveformButton"))
        self.gridLayout.addWidget(self.addWaveformButton, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.waveformList = QtGui.QListView(self.waveformSelectionFrame)
        self.waveformList.setObjectName(_fromUtf8("waveformList"))
        self.gridLayout.addWidget(self.waveformList, 0, 0, 1, 4)
        self.waveformEditFrame = QtGui.QFrame(self.splitter)
        self.waveformEditFrame.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waveformEditFrame.sizePolicy().hasHeightForWidth())
        self.waveformEditFrame.setSizePolicy(sizePolicy)
        self.waveformEditFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.waveformEditFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.waveformEditFrame.setObjectName(_fromUtf8("waveformEditFrame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.waveformEditFrame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.interphaseGapWidthLabel = QtGui.QLabel(self.waveformEditFrame)
        self.interphaseGapWidthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.interphaseGapWidthLabel.setObjectName(_fromUtf8("interphaseGapWidthLabel"))
        self.gridLayout_3.addWidget(self.interphaseGapWidthLabel, 4, 0, 1, 1)
        self.pulseWidthLabel = QtGui.QLabel(self.waveformEditFrame)
        self.pulseWidthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pulseWidthLabel.setObjectName(_fromUtf8("pulseWidthLabel"))
        self.gridLayout_3.addWidget(self.pulseWidthLabel, 5, 0, 1, 1)
        self.setupWidthLabel = QtGui.QLabel(self.waveformEditFrame)
        self.setupWidthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.setupWidthLabel.setObjectName(_fromUtf8("setupWidthLabel"))
        self.gridLayout_3.addWidget(self.setupWidthLabel, 6, 0, 1, 1)
        self.amplitudeLabel = QtGui.QLabel(self.waveformEditFrame)
        self.amplitudeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.amplitudeLabel.setObjectName(_fromUtf8("amplitudeLabel"))
        self.gridLayout_3.addWidget(self.amplitudeLabel, 2, 0, 1, 1)
        self.shortTimeWidthBox = RoundedSpinBox(self.waveformEditFrame)
        self.shortTimeWidthBox.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.shortTimeWidthBox.setDecimals(3)
        self.shortTimeWidthBox.setMinimum(31.25)
        self.shortTimeWidthBox.setMaximum(1000.0)
        self.shortTimeWidthBox.setSingleStep(31.25)
        self.shortTimeWidthBox.setObjectName(_fromUtf8("shortTimeWidthBox"))
        self.gridLayout_3.addWidget(self.shortTimeWidthBox, 3, 2, 1, 1)
        self.shortTimeWidthLabel = QtGui.QLabel(self.waveformEditFrame)
        self.shortTimeWidthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.shortTimeWidthLabel.setObjectName(_fromUtf8("shortTimeWidthLabel"))
        self.gridLayout_3.addWidget(self.shortTimeWidthLabel, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 9, 2, 1, 1)
        self.numberOfPulsesLabel = QtGui.QLabel(self.waveformEditFrame)
        self.numberOfPulsesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.numberOfPulsesLabel.setObjectName(_fromUtf8("numberOfPulsesLabel"))
        self.gridLayout_3.addWidget(self.numberOfPulsesLabel, 7, 0, 1, 1)
        self.nameLabel = QtGui.QLabel(self.waveformEditFrame)
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setObjectName(_fromUtf8("nameLabel"))
        self.gridLayout_3.addWidget(self.nameLabel, 1, 0, 1, 1)
        self.NameEdit = QtGui.QLineEdit(self.waveformEditFrame)
        self.NameEdit.setObjectName(_fromUtf8("NameEdit"))
        self.gridLayout_3.addWidget(self.NameEdit, 1, 2, 1, 1)
        self.amplitudeBox = RoundedSpinBox(self.waveformEditFrame)
        self.amplitudeBox.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.amplitudeBox.setMaximum(100.0)
        self.amplitudeBox.setSingleStep(0.1)
        self.amplitudeBox.setObjectName(_fromUtf8("amplitudeBox"))
        self.gridLayout_3.addWidget(self.amplitudeBox, 2, 2, 1, 1)
        self.interphaseGapWidthBox = RoundedSpinBox(self.waveformEditFrame)
        self.interphaseGapWidthBox.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.interphaseGapWidthBox.setDecimals(3)
        self.interphaseGapWidthBox.setMinimum(31.25)
        self.interphaseGapWidthBox.setMaximum(1000.0)
        self.interphaseGapWidthBox.setSingleStep(31.25)
        self.interphaseGapWidthBox.setProperty("value", 31.25)
        self.interphaseGapWidthBox.setObjectName(_fromUtf8("interphaseGapWidthBox"))
        self.gridLayout_3.addWidget(self.interphaseGapWidthBox, 4, 2, 1, 1)
        self.pulseWidthBox = RoundedSpinBox(self.waveformEditFrame)
        self.pulseWidthBox.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.pulseWidthBox.setDecimals(3)
        self.pulseWidthBox.setMinimum(15.625)
        self.pulseWidthBox.setMaximum(500.0)
        self.pulseWidthBox.setSingleStep(15.625)
        self.pulseWidthBox.setProperty("value", 15.625)
        self.pulseWidthBox.setObjectName(_fromUtf8("pulseWidthBox"))
        self.gridLayout_3.addWidget(self.pulseWidthBox, 5, 2, 1, 1)
        self.setupWidthBox = RoundedSpinBox(self.waveformEditFrame)
        self.setupWidthBox.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.setupWidthBox.setDecimals(3)
        self.setupWidthBox.setMinimum(31.25)
        self.setupWidthBox.setMaximum(1000.0)
        self.setupWidthBox.setSingleStep(31.25)
        self.setupWidthBox.setObjectName(_fromUtf8("setupWidthBox"))
        self.gridLayout_3.addWidget(self.setupWidthBox, 6, 2, 1, 1)
        self.numberOfPulsesBox = QtGui.QDoubleSpinBox(self.waveformEditFrame)
        self.numberOfPulsesBox.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.numberOfPulsesBox.setSuffix(_fromUtf8(""))
        self.numberOfPulsesBox.setDecimals(0)
        self.numberOfPulsesBox.setMaximum(127.0)
        self.numberOfPulsesBox.setSingleStep(1.0)
        self.numberOfPulsesBox.setObjectName(_fromUtf8("numberOfPulsesBox"))
        self.gridLayout_3.addWidget(self.numberOfPulsesBox, 7, 2, 1, 1)
        self.verticalLayout.addWidget(self.splitter)
        self.acceptButton = QtGui.QDialogButtonBox(WaveformDialog)
        self.acceptButton.setOrientation(QtCore.Qt.Horizontal)
        self.acceptButton.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.acceptButton.setObjectName(_fromUtf8("acceptButton"))
        self.verticalLayout.addWidget(self.acceptButton)

        self.retranslateUi(WaveformDialog)
        QtCore.QObject.connect(self.acceptButton, QtCore.SIGNAL(_fromUtf8("accepted()")), WaveformDialog.accept)
        QtCore.QObject.connect(self.acceptButton, QtCore.SIGNAL(_fromUtf8("rejected()")), WaveformDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(WaveformDialog)

    def retranslateUi(self, WaveformDialog):
        WaveformDialog.setWindowTitle(_translate("WaveformDialog", "Waveform Configuration", None))
        self.delWaveformButton.setText(_translate("WaveformDialog", "Delete", None))
        self.addWaveformButton.setText(_translate("WaveformDialog", "Add", None))
        self.interphaseGapWidthLabel.setText(_translate("WaveformDialog", "Interphase Gap Width", None))
        self.pulseWidthLabel.setText(_translate("WaveformDialog", "Pulse Width", None))
        self.setupWidthLabel.setText(_translate("WaveformDialog", "Setup Width", None))
        self.amplitudeLabel.setText(_translate("WaveformDialog", "Amplitude", None))
        self.shortTimeWidthBox.setSuffix(_translate("WaveformDialog", " us", None))
        self.shortTimeWidthLabel.setText(_translate("WaveformDialog", "Short Time Width", None))
        self.numberOfPulsesLabel.setText(_translate("WaveformDialog", "Number of Pulses", None))
        self.nameLabel.setText(_translate("WaveformDialog", "Name", None))
        self.amplitudeBox.setSuffix(_translate("WaveformDialog", " uA", None))
        self.interphaseGapWidthBox.setSuffix(_translate("WaveformDialog", " us", None))
        self.pulseWidthBox.setSuffix(_translate("WaveformDialog", " us", None))
        self.setupWidthBox.setSuffix(_translate("WaveformDialog", " us", None))

from roundedspinbox import RoundedSpinBox
